<?php
/****************************************************************************************

    Computations related to chi square test.
    Implementation limited to the case of contingency table with one column.
    
    @copyright  Thierry Graff
    @license    GPL - conforms to file LICENCE located in root directory of current repository.
    
    @history    2016-11-27 23:23:59+01:00, Thierry Graff : Creation for jetheme
    @history    2026-02-26 22:16:02+01:00, Thierry Graff : Inclusion in tiglib
****************************************************************************************/

namespace tiglib\stats;

class chi2 {

    /**
        Returns an array containing 2 elements: the chi2 value and the p-value.
        @param  $df Degree of freedom
        @param  $O  Observed distribution
        @param  $E  Expected distribution
    **/
    public static function chi2AndProba(int $df, array $O, array $E) {
        $chi2 = self::chi2($O, $E);
        return [
            $chi2,
            self::chi2Proba($chi2, $df),
        ];
    }
    
    // in case: https://www.socscistatistics.com/pvalues/chidistribution/calculator/
    
    /**
        Computes the chi square value to compare observed and expected values,
        for contingency table with only one column.
        @param  $O  Array containing observed values (regular or associative)
        @param  $E  Array containing expected values (regular or associative)
    **/
    public static function chi2(array $O, array $E): int|float{
        $res = 0;
        $N = count($O);
        $keysE = array_keys($E);
        $keysO = array_keys($O);
        for($i=0; $i < $N; $i++){
            if($E[$keysE[$i]] != 0){
                $res += pow($O[$keysO[$i]] - $E[$keysE[$i]], 2) / $E[$keysE[$i]];
            }
        }
        return $res;
    }
    
    //
    //
    // Following code = adaptation of code generated by chatgpt
    // NEEDS VERIFICATIONS AND MORE TESTS
    //
    //
/*
cephes
https://netlib.org/cephes/singldoc.html#chdtr
chdtrf.c
y = chdtr( v, x ) = igam( v/2.0, x/2.0

https://github.com/jeremybarnes/cephes
Mirror of the Cephes C source for reference

assert_close(hcephes_chdtr(4, 5), 0.7127025048163542);
*/
    
    // --- chi-square p-value (upper tail) ---
    public static function chi2Proba(float $chi2, float $df): float {
        return self::gammq($df / 2.0, $chi2 / 2.0);
    }
    
    // --- regularized upper incomplete gamma Q(a,x) ---
    private static function gammq(float $a, float $x): float {
        if ($x < 0.0 || $a <= 0.0) {
            return NAN;
        }
        if ($x < $a + 1.0) {
            // use series → compute P, then Q = 1 - P
            return 1.0 - self::gser($a, $x);
        } else {
            // use continued fraction directly for Q
            return self::gcf($a, $x);
        }
    }
    
    // --- log gamma (Lanczos approximation) ---
    private static function gammln(float $xx): float {
        $cof = [
            76.18009172947146,   -86.50532032941677,
            24.01409824083091,   -1.231739572450155,
            0.1208650973866179e-2, -0.5395239384953e-5
        ];
        $x = $xx - 1.0;
        $tmp = $x + 5.5;
        $tmp -= ($x + 0.5) * log($tmp);
        $ser = 1.000000000190015;
        for ($j = 0; $j < 6; $j++) {
            $x += 1.0;
            $ser += $cof[$j] / $x;
        }
        return -$tmp + log(2.5066282746310005 * $ser);
    }
    
    // --- series representation of lower gamma P(a,x) ---
    private static function gser(float $a, float $x): float {
        $ITMAX = 100;
        $EPS = 3.0e-7;
    
        $sum = 1.0 / $a;
        $del = $sum;
        $ap = $a;
    
        for ($n = 1; $n <= $ITMAX; $n++) {
            $ap += 1.0;
            $del *= $x / $ap;
            $sum += $del;
            if (abs($del) < abs($sum) * $EPS) {
                return $sum * exp(-$x + $a * log($x) - self::gammln($a));
            }
        }
        return $sum * exp(-$x + $a * log($x) - self::gammln($a));
    }
    
    // --- continued fraction for upper gamma Q(a,x) ---
    private static function gcf(float $a, float $x): float {
        $ITMAX = 100;
        $EPS = 3.0e-7;
        $FPMIN = 1e-30;
    
        $b = $x + 1.0 - $a;
        $c = 1.0 / $FPMIN;
        $d = 1.0 / $b;
        $h = $d;
    
        for ($i = 1; $i <= $ITMAX; $i++) {
            $an = -$i * ($i - $a);
            $b += 2.0;
            $d = $an * $d + $b;
            if (abs($d) < $FPMIN) $d = $FPMIN;
            $c = $b + $an / $c;
            if (abs($c) < $FPMIN) $c = $FPMIN;
            $d = 1.0 / $d;
            $del = $d * $c;
            $h *= $del;
            if (abs($del - 1.0) < $EPS) break;
        }
    
        return exp(-$x + $a * log($x) - self::gammln($a)) * $h;
    }
    
}// end class

